"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { format, parseISO } from "date-fns";
import { toast } from "sonner";
import type { AiInsight, InsightType } from "@/types";

const TYPE_META: Record<
  InsightType,
  { tag: string; color: string }
> = {
  pattern: { tag: "Pattern", color: "var(--sf-ring-mind)" },
  prediction: { tag: "Prediction", color: "var(--sf-ring-fuel)" },
  correlation: { tag: "Correlation", color: "var(--sf-ring-flow)" },
  motivation: { tag: "Note", color: "var(--sf-accent)" },
};

export default function InsightsPage() {
  const [insights, setInsights] = useState<AiInsight[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    fetchInsights();
  }, []);

  async function fetchInsights() {
    const supabase = createClient();
    const { data } = await supabase
      .from("ai_insights")
      .select("*")
      .not("message", "like", "perfect-day-bonus:%")
      .order("generated_at", { ascending: false })
      .limit(20);
    setInsights(data ?? []);
    setLoading(false);
  }

  async function refresh() {
    setGenerating(true);
    try {
      const res = await fetch("/api/insights", { method: "POST" });
      if (!res.ok) {
        const body = await res.json();
        throw new Error(body.error ?? "Failed to generate insights");
      }
      toast.success("New insights generated.");
      await fetchInsights();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setGenerating(false);
    }
  }

  async function dismiss(id: string) {
    const supabase = createClient();
    await supabase.from("ai_insights").update({ is_read: true }).eq("id", id);
    setInsights((prev) => prev.filter((i) => i.id !== id));
  }

  return (
    <div className="mx-auto max-w-6xl">
      <div className="mb-2 flex items-end justify-between gap-4">
        <div>
          <div className="sf-eyebrow">This week</div>
          <h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl lg:text-[32px]">
            Insights
          </h1>
        </div>
        <button
          onClick={refresh}
          disabled={generating}
          className="inline-flex items-center gap-2 rounded-lg border px-4 py-2 text-sm font-semibold disabled:opacity-60"
          style={{
            background: "var(--sf-surface-2)",
            borderColor: "var(--sf-border)",
            color: "var(--sf-text)",
          }}
        >
          <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
            <path
              d="M11.5 6.5a5 5 0 11-1.5-3.5M11.5 1v3.5H8"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
          {generating ? "Refreshing…" : "Refresh insights"}
        </button>
      </div>
      <p
        className="mb-7 max-w-[560px] text-sm"
        style={{ color: "var(--sf-text-3)" }}
      >
        Patterns and predictions from your last 30 days. Generated by Claude.
      </p>

      {loading ? (
        <div className="grid gap-3.5 lg:grid-cols-2">
          {Array.from({ length: 4 }).map((_, i) => (
            <div
              key={i}
              className="h-40 animate-pulse rounded-2xl border"
              style={{
                background: "var(--sf-surface)",
                borderColor: "var(--sf-border)",
              }}
            />
          ))}
        </div>
      ) : insights.length === 0 ? (
        <div className="py-16 text-center">
          <div
            className="mb-4 inline-flex h-16 w-16 items-center justify-center rounded-2xl"
            style={{ background: "var(--sf-surface-2)" }}
          >
            <span className="text-3xl">✨</span>
          </div>
          <h3 className="mb-2 text-lg font-semibold">No insights yet</h3>
          <p
            className="mx-auto mb-6 max-w-sm text-sm"
            style={{ color: "var(--sf-text-3)" }}
          >
            Log a few more days and we'll surface patterns. Or generate now.
          </p>
          <button
            onClick={refresh}
            disabled={generating}
            className="rounded-lg px-4 py-2 text-sm font-semibold disabled:opacity-60"
            style={{ background: "var(--sf-text)", color: "var(--sf-bg)" }}
          >
            {generating ? "Generating…" : "Generate insights"}
          </button>
        </div>
      ) : (
        <div className="grid gap-3.5 lg:grid-cols-2">
          {insights.map((ins) => {
            const meta = TYPE_META[ins.insight_type];
            // Split on first sentence-ending punctuation, falling back to first newline.
            const msg = ins.message.trim();
            let cut = -1;
            for (let i = 0; i < msg.length; i++) {
              const ch = msg[i];
              if (
                (ch === "." || ch === "!" || ch === "?") &&
                msg[i + 1] !== undefined &&
                msg[i + 1] !== ch
              ) {
                cut = i + 1;
                break;
              }
              if (ch === "\n") {
                cut = i;
                break;
              }
            }
            const headline = cut > 0 ? msg.slice(0, cut).trim() : msg;
            const body = cut > 0 ? msg.slice(cut).trim() : "";
            return (
              <div
                key={ins.id}
                className="relative overflow-hidden rounded-2xl border p-6"
                style={{
                  background: "var(--sf-surface)",
                  borderColor: "var(--sf-border)",
                }}
              >
                <div
                  className="absolute bottom-0 left-0 top-0 w-[3px]"
                  style={{ background: meta.color }}
                />
                <div className="mb-3.5 flex items-start justify-between">
                  <span
                    className="inline-flex items-center rounded-full border px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-[0.06em]"
                    style={{
                      background: `color-mix(in oklab, ${meta.color} 14%, transparent)`,
                      color: meta.color,
                      borderColor: `color-mix(in oklab, ${meta.color} 28%, transparent)`,
                    }}
                  >
                    {meta.tag}
                  </span>
                  <button
                    onClick={() => dismiss(ins.id)}
                    aria-label="Dismiss"
                    className="p-0.5"
                    style={{ color: "var(--sf-text-3)" }}
                  >
                    <svg
                      width="14"
                      height="14"
                      viewBox="0 0 14 14"
                      fill="none"
                    >
                      <path
                        d="M3 3l8 8M11 3l-8 8"
                        stroke="currentColor"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                      />
                    </svg>
                  </button>
                </div>
                <h3 className="mb-2.5 text-lg font-semibold leading-snug tracking-tight">
                  {headline || ins.message}
                </h3>
                {body && (
                  <p
                    className="text-sm leading-relaxed"
                    style={{ color: "var(--sf-text-2)" }}
                  >
                    {body}
                  </p>
                )}
                <div
                  className="mt-4 text-[11px]"
                  style={{ color: "var(--sf-text-3)" }}
                >
                  Generated {format(parseISO(ins.generated_at), "MMM d")}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
