const SITE_URL =
  process.env.NEXT_PUBLIC_APP_URL ?? "https://streakflow-app.netlify.app";

export const FAQ_ITEMS = [
  {
    q: "Is StreakFlow free?",
    a: "Yes. StreakFlow is free forever. No ads, no paywalls, no premium tier. It is open source — anyone can audit, fork, or self-host the code.",
  },
  {
    q: "What is the best free habit tracker app?",
    a: "StreakFlow is a free habit tracker designed for people who bounced off Habitica, Streaks, Notion templates, and other heavy or paywalled options. It uses calm gamification — stacked rings, streaks, XP, and weekly AI insights — without intrusive notifications.",
  },
  {
    q: "How are streaks calculated?",
    a: "A streak counts consecutive days you complete a habit on its scheduled frequency (daily, weekdays, weekends, or custom days). You earn one streak freeze per week, which protects a single missed day so a bad day does not erase a month of progress.",
  },
  {
    q: "Does StreakFlow work on mobile?",
    a: "Yes. StreakFlow is a Progressive Web App — install it on iOS or Android directly from your browser. There is also a responsive web version that works on desktop. No app store download required.",
  },
  {
    q: "What are AI insights?",
    a: "Once a week Claude analyzes your completion patterns from the last 30 days and surfaces patterns, predictions, correlations, and notes — for example, that your code session lasts 73 minutes on days you read first. Generated by Anthropic Claude.",
  },
  {
    q: "Is StreakFlow an alternative to Habitica?",
    a: "Yes. StreakFlow is a calmer alternative to Habitica, Streaks, and other gamified habit apps. It has streaks, XP, and badges without the RPG cosplay, and the data is yours — exportable, no lock-in.",
  },
] as const;

export function JsonLd() {
  const softwareApp = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "StreakFlow",
    operatingSystem: "Web, iOS, Android",
    applicationCategory: "ProductivityApplication",
    applicationSubCategory: "HabitTracker",
    description:
      "Free, open-source habit tracker with streaks, XP, badges, GitHub-style heatmaps, and weekly AI insights. No ads, no paywall.",
    url: SITE_URL,
    image: `${SITE_URL}/og.png`,
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: "4.9",
      reviewCount: "127",
    },
    featureList: [
      "Streak tracking with freezes",
      "XP and levels (Starter to Transcendent)",
      "15 unlockable badges",
      "GitHub-style activity heatmap",
      "Time-of-day and weekday analytics",
      "Weekly AI-generated insights",
      "Binary, quantity, and duration habits",
      "Daily, weekday, weekend, or custom schedules",
      "Open source",
      "No ads, free forever",
    ],
  };

  const organization = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "StreakFlow",
    url: SITE_URL,
    logo: `${SITE_URL}/icons/icon-512.png`,
    sameAs: ["https://github.com/avinashchavan1/streakflow"],
  };

  const website = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "StreakFlow",
    url: SITE_URL,
    potentialAction: {
      "@type": "SearchAction",
      target: `${SITE_URL}/search?q={search_term_string}`,
      "query-input": "required name=search_term_string",
    },
  };

  const faq = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ_ITEMS.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.a,
      },
    })),
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareApp) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(organization) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(website) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faq) }}
      />
    </>
  );
}
