import Link from "next/link";
import { StackedRing } from "@/components/dashboard/StackedRing";

const FEATURES = [
  {
    icon: "🔥",
    title: "Streaks",
    desc: "Days, weeks, milestones. With one freeze a week so a bad day doesn't erase a month.",
  },
  {
    icon: "⚡",
    title: "XP",
    desc: "Earn for every check-in. Multipliers kick in at day 7, 30, and 100.",
  },
  {
    icon: "🏆",
    title: "Badges",
    desc: "15 to collect — from First Step to Transcendent. Unlocked, never bought.",
  },
  {
    icon: "📊",
    title: "Analytics",
    desc: "GitHub-style heatmaps, completion %, time-of-day patterns. The data is yours.",
  },
  {
    icon: "✨",
    title: "AI insights",
    desc: "Weekly patterns and predictions, generated by Claude. Dry, useful, never preachy.",
  },
];

const HERO_RINGS = [
  { c: "#ff2d55", n: "Workout", v: "45/45 min", value: 1.0 },
  { c: "#ffb340", n: "Water", v: "5/8 glasses", value: 0.62 },
  { c: "#00d9b2", n: "Meditate", v: "10/10 min", value: 1.0 },
  { c: "#af52de", n: "Read", v: "12/30 min", value: 0.4 },
];

export default function LandingPage() {
  return (
    <div
      className="flex min-h-screen flex-col"
      style={{ background: "var(--sf-bg)", color: "var(--sf-text)" }}
    >
      {/* Nav */}
      <nav
        className="sticky top-0 z-10 flex items-center justify-between border-b px-6 py-5 backdrop-blur-xl lg:px-12"
        style={{
          background: "rgba(16,14,12,0.7)",
          borderColor: "var(--sf-border)",
        }}
      >
        <div className="flex items-center gap-2.5">
          <div
            className="relative h-7 w-7 rounded-lg"
            style={{
              background:
                "conic-gradient(from 90deg, var(--sf-ring-move), var(--sf-ring-fuel), var(--sf-ring-mind), var(--sf-ring-move))",
            }}
          >
            <div
              className="absolute inset-1.5 rounded"
              style={{ background: "var(--sf-bg)" }}
            />
          </div>
          <div className="text-[15px] font-semibold tracking-tight">
            StreakFlow
          </div>
        </div>
        <div className="flex items-center gap-4 sm:gap-6">
          <Link
            href="/login"
            className="text-sm hidden sm:block"
            style={{ color: "var(--sf-text-2)" }}
          >
            Sign in
          </Link>
          <Link
            href="/signup"
            className="rounded-lg px-4 py-2 text-sm font-semibold"
            style={{ background: "var(--sf-text)", color: "var(--sf-bg)" }}
          >
            Start free
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative mx-auto grid w-full max-w-[1280px] items-center gap-10 px-6 py-16 lg:grid-cols-[1.1fr_1fr] lg:gap-16 lg:px-12 lg:py-24">
        <div
          aria-hidden
          className="pointer-events-none absolute"
          style={{
            left: "50%",
            top: 60,
            width: 600,
            height: 600,
            transform: "translateX(20%)",
            background:
              "radial-gradient(circle, rgba(255,45,85,0.08), transparent 60%)",
          }}
        />
        <div className="relative">
          <div
            className="mb-6 inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs"
            style={{
              background: "var(--sf-surface)",
              borderColor: "var(--sf-border)",
              color: "var(--sf-text-2)",
            }}
          >
            <span
              className="h-1.5 w-1.5 rounded-full"
              style={{ background: "var(--sf-ring-mind)" }}
            />
            Now with weekly AI insights
          </div>
          <h1
            className="mb-6 text-5xl font-semibold leading-[0.95] tracking-tight sm:text-6xl lg:text-[72px]"
            style={{ letterSpacing: "-0.04em" }}
          >
            Habits that
            <br />
            <span
              style={{
                background:
                  "linear-gradient(90deg, var(--sf-ring-move), var(--sf-ring-fuel))",
                WebkitBackgroundClip: "text",
                WebkitTextFillColor: "transparent",
                backgroundClip: "text",
              }}
            >
              actually stick.
            </span>
          </h1>
          <p
            className="mb-9 max-w-[460px] text-lg leading-relaxed"
            style={{ color: "var(--sf-text-2)" }}
          >
            One ring per habit, one minute per check-in. Calm gamification for
            people who bounced off Habitica and Notion templates alike.
          </p>
          <div className="flex items-center gap-3">
            <Link
              href="/signup"
              className="inline-flex items-center gap-2 rounded-lg px-5 py-3.5 text-[15px] font-semibold"
              style={{ background: "var(--sf-text)", color: "var(--sf-bg)" }}
            >
              Start free
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path
                  d="M3 7h8M7 3l4 4-4 4"
                  stroke="currentColor"
                  strokeWidth="1.7"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </Link>
            <Link
              href="/login"
              className="rounded-lg border px-5 py-3.5 text-[15px] font-semibold"
              style={{
                background: "var(--sf-surface-2)",
                borderColor: "var(--sf-border)",
                color: "var(--sf-text)",
              }}
            >
              Sign in
            </Link>
          </div>
          <div
            className="mt-10 flex flex-wrap gap-7 text-xs"
            style={{ color: "var(--sf-text-3)" }}
          >
            {["Free forever", "No ads, ever", "Open source"].map((t) => (
              <div key={t} className="flex items-center gap-1.5">
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                  <path
                    d="M3 7l3 3 5-6"
                    stroke="var(--sf-success)"
                    strokeWidth="1.7"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
                {t}
              </div>
            ))}
          </div>
        </div>

        {/* Hero rings card */}
        <div
          className="relative flex flex-col items-center gap-6 rounded-[28px] border p-8 lg:p-10"
          style={{
            background:
              "radial-gradient(ellipse at top, rgba(255,179,64,0.12), transparent 70%), var(--sf-surface)",
            borderColor: "var(--sf-border)",
          }}
        >
          <StackedRing
            size={300}
            stroke={20}
            gap={4}
            rings={HERO_RINGS.map((r) => ({
              key: r.n,
              color: r.c,
              value: r.value,
            }))}
          >
            <div className="sf-eyebrow">Today</div>
            <div className="sf-num mt-1 text-[64px] font-semibold leading-none">
              76
              <span className="text-3xl" style={{ color: "var(--sf-text-3)" }}>
                %
              </span>
            </div>
            <div className="mt-2 text-sm" style={{ color: "var(--sf-text-2)" }}>
              Halfway through
            </div>
          </StackedRing>
          <div className="grid w-full grid-cols-2 gap-2">
            {HERO_RINGS.map((r) => (
              <div
                key={r.n}
                className="flex items-center gap-2 rounded-lg border px-3 py-2"
                style={{
                  background: "var(--sf-surface-2)",
                  borderColor: "var(--sf-border)",
                }}
              >
                <div
                  className="h-2 w-2 rounded-full"
                  style={{ background: r.c }}
                />
                <span className="flex-1 text-xs font-medium">{r.n}</span>
                <span
                  className="sf-num text-[11px]"
                  style={{ color: "var(--sf-text-3)" }}
                >
                  {r.v}
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="mx-auto w-full max-w-[1280px] px-6 py-16 lg:px-12">
        <div className="sf-eyebrow mb-4 text-center">What you get</div>
        <h2 className="mb-14 text-center text-4xl font-semibold tracking-tight lg:text-[40px]">
          Five rings. No nonsense.
        </h2>
        <div className="grid grid-cols-1 gap-3.5 sm:grid-cols-2 lg:grid-cols-5">
          {FEATURES.map((f) => (
            <div
              key={f.title}
              className="rounded-2xl border p-5"
              style={{
                background: "var(--sf-surface)",
                borderColor: "var(--sf-border)",
              }}
            >
              <div className="mb-3.5 text-2xl">{f.icon}</div>
              <div className="mb-1.5 text-sm font-semibold">{f.title}</div>
              <div
                className="text-xs leading-relaxed"
                style={{ color: "var(--sf-text-3)" }}
              >
                {f.desc}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer
        className="mx-auto mt-16 flex w-full max-w-[1280px] items-center justify-between border-t px-6 py-10 lg:px-12"
        style={{ borderColor: "var(--sf-border)" }}
      >
        <div className="text-xs" style={{ color: "var(--sf-text-3)" }}>
          © 2026 StreakFlow
        </div>
        <div
          className="flex gap-5 text-xs"
          style={{ color: "var(--sf-text-3)" }}
        >
          <a
            href="https://github.com/avinashchavan1/streakflow"
            target="_blank"
            rel="noreferrer"
          >
            GitHub
          </a>
          <a href="#">Privacy</a>
          <a href="#">Manifesto</a>
        </div>
      </footer>
    </div>
  );
}
