import type { Metadata } from "next";
import Link from "next/link";
import { StackedRing } from "@/components/dashboard/StackedRing";
import { JsonLd, FAQ_ITEMS } from "@/components/seo/JsonLd";

export const metadata: Metadata = {
  title: "Free Habit Tracker App — Streaks, XP & AI Insights | StreakFlow",
  description:
    "The free habit tracker app for daily routines. Streaks, XP, badges, GitHub-style heatmaps, and weekly AI insights. No ads, open source, works on iOS, Android, and web.",
  alternates: { canonical: "/" },
};

const HOW_IT_WORKS = [
  {
    step: "1",
    title: "Add habits",
    desc: "Pick from templates or build your own. Binary, quantity, or duration. Daily, weekdays, weekends, or custom days.",
  },
  {
    step: "2",
    title: "Check in daily",
    desc: "One tap closes a ring. Streaks build. XP banks with multipliers at day 7, 30, and 100.",
  },
  {
    step: "3",
    title: "See patterns",
    desc: "GitHub-style heatmap, completion percentages, time-of-day patterns, plus weekly AI insights generated by Claude.",
  },
];

const COMPARE_ROWS = [
  { feature: "Free forever", sf: true, habitica: false, streaks: false, notion: true },
  { feature: "No ads", sf: true, habitica: false, streaks: true, notion: true },
  { feature: "Open source", sf: true, habitica: true, streaks: false, notion: false },
  { feature: "Streaks & freezes", sf: true, habitica: true, streaks: true, notion: false },
  { feature: "GitHub-style heatmap", sf: true, habitica: false, streaks: false, notion: false },
  { feature: "Weekly AI insights", sf: true, habitica: false, streaks: false, notion: false },
  { feature: "Works in browser", sf: true, habitica: true, streaks: false, notion: true },
  { feature: "PWA installable", sf: true, habitica: false, streaks: false, notion: false },
];

const FEATURES = [
  {
    icon: "🔥",
    title: "Streaks",
    desc: "Days, weeks, milestones. With one freeze a week so a bad day doesn't erase a month.",
  },
  {
    icon: "⚡",
    title: "XP",
    desc: "Earn for every check-in. Multipliers kick in at day 7, 30, and 100.",
  },
  {
    icon: "🏆",
    title: "Badges",
    desc: "15 to collect — from First Step to Transcendent. Unlocked, never bought.",
  },
  {
    icon: "📊",
    title: "Analytics",
    desc: "GitHub-style heatmaps, completion %, time-of-day patterns. The data is yours.",
  },
  {
    icon: "✨",
    title: "AI insights",
    desc: "Weekly patterns and predictions, generated by Claude. Dry, useful, never preachy.",
  },
];

const HERO_RINGS = [
  { c: "#ff2d55", n: "Workout", v: "45/45 min", value: 1.0 },
  { c: "#ffb340", n: "Water", v: "5/8 glasses", value: 0.62 },
  { c: "#00d9b2", n: "Meditate", v: "10/10 min", value: 1.0 },
  { c: "#af52de", n: "Read", v: "12/30 min", value: 0.4 },
];

export default function LandingPage() {
  return (
    <div
      className="flex min-h-screen flex-col overflow-x-hidden"
      style={{ background: "var(--sf-bg)", color: "var(--sf-text)" }}
    >
      <JsonLd />
      {/* Nav */}
      <nav
        className="sticky top-0 z-10 flex items-center justify-between border-b px-6 py-5 backdrop-blur-xl lg:px-12"
        style={{
          background: "rgba(16,14,12,0.7)",
          borderColor: "var(--sf-border)",
        }}
      >
        <div className="flex items-center gap-2.5">
          <div
            className="relative h-7 w-7 rounded-lg"
            style={{
              background:
                "conic-gradient(from 90deg, var(--sf-ring-move), var(--sf-ring-fuel), var(--sf-ring-mind), var(--sf-ring-move))",
            }}
          >
            <div
              className="absolute inset-1.5 rounded"
              style={{ background: "var(--sf-bg)" }}
            />
          </div>
          <div className="text-[15px] font-semibold tracking-tight">
            StreakFlow
          </div>
        </div>
        <div className="flex items-center gap-4 sm:gap-6">
          <Link
            href="/login"
            className="text-sm hidden sm:block"
            style={{ color: "var(--sf-text-2)" }}
          >
            Sign in
          </Link>
          <Link
            href="/signup"
            className="rounded-lg px-4 py-2 text-sm font-semibold"
            style={{ background: "var(--sf-text)", color: "var(--sf-bg)" }}
          >
            Start free
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative mx-auto grid w-full max-w-[1280px] items-center gap-10 px-6 py-16 lg:grid-cols-[1.1fr_1fr] lg:gap-16 lg:px-12 lg:py-24">
        <div
          aria-hidden
          className="pointer-events-none absolute"
          style={{
            left: "50%",
            top: 60,
            width: 600,
            height: 600,
            transform: "translateX(20%)",
            background:
              "radial-gradient(circle, rgba(255,45,85,0.08), transparent 60%)",
          }}
        />
        <div className="relative">
          <div
            className="mb-6 inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs"
            style={{
              background: "var(--sf-surface)",
              borderColor: "var(--sf-border)",
              color: "var(--sf-text-2)",
            }}
          >
            <span
              className="h-1.5 w-1.5 rounded-full"
              style={{ background: "var(--sf-ring-mind)" }}
            />
            Now with weekly AI insights
          </div>
          <h1
            className="mb-6 text-5xl font-semibold leading-[0.95] tracking-tight sm:text-6xl lg:text-[72px]"
            style={{ letterSpacing: "-0.04em" }}
          >
            The free habit
            <br />
            tracker that{" "}
            <span
              style={{
                background:
                  "linear-gradient(90deg, var(--sf-ring-move), var(--sf-ring-fuel))",
                WebkitBackgroundClip: "text",
                WebkitTextFillColor: "transparent",
                backgroundClip: "text",
              }}
            >
              actually sticks.
            </span>
          </h1>
          <p
            className="mb-9 max-w-[520px] text-lg leading-relaxed"
            style={{ color: "var(--sf-text-2)" }}
          >
            Build daily habits with streaks, XP, badges, and weekly AI
            insights. One ring per habit, one minute per check-in. Free
            forever, no ads, open source — a calm alternative to Habitica and
            Streaks.
          </p>
          <div className="flex items-center gap-3">
            <Link
              href="/signup"
              className="inline-flex items-center gap-2 rounded-lg px-5 py-3.5 text-[15px] font-semibold"
              style={{ background: "var(--sf-text)", color: "var(--sf-bg)" }}
            >
              Start free
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path
                  d="M3 7h8M7 3l4 4-4 4"
                  stroke="currentColor"
                  strokeWidth="1.7"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </Link>
            <Link
              href="/login"
              className="rounded-lg border px-5 py-3.5 text-[15px] font-semibold"
              style={{
                background: "var(--sf-surface-2)",
                borderColor: "var(--sf-border)",
                color: "var(--sf-text)",
              }}
            >
              Sign in
            </Link>
          </div>
          <div
            className="mt-10 flex flex-wrap gap-7 text-xs"
            style={{ color: "var(--sf-text-3)" }}
          >
            {["Free forever", "No ads, ever", "Open source"].map((t) => (
              <div key={t} className="flex items-center gap-1.5">
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                  <path
                    d="M3 7l3 3 5-6"
                    stroke="var(--sf-success)"
                    strokeWidth="1.7"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
                {t}
              </div>
            ))}
          </div>
        </div>

        {/* Hero rings card */}
        <div
          className="relative flex w-full flex-col items-center gap-6 rounded-[28px] border p-5 sm:p-8 lg:p-10"
          style={{
            background:
              "radial-gradient(ellipse at top, rgba(255,179,64,0.12), transparent 70%), var(--sf-surface)",
            borderColor: "var(--sf-border)",
          }}
        >
          <StackedRing
            size={300}
            stroke={20}
            gap={4}
            rings={HERO_RINGS.map((r) => ({
              key: r.n,
              color: r.c,
              value: r.value,
            }))}
          >
            <div className="sf-eyebrow">Today</div>
            <div className="sf-num mt-1 text-[64px] font-semibold leading-none">
              76
              <span className="text-3xl" style={{ color: "var(--sf-text-3)" }}>
                %
              </span>
            </div>
            <div className="mt-2 text-sm" style={{ color: "var(--sf-text-2)" }}>
              Halfway through
            </div>
          </StackedRing>
          <div className="grid w-full grid-cols-2 gap-2">
            {HERO_RINGS.map((r) => (
              <div
                key={r.n}
                className="flex items-center gap-2 rounded-lg border px-3 py-2"
                style={{
                  background: "var(--sf-surface-2)",
                  borderColor: "var(--sf-border)",
                }}
              >
                <div
                  className="h-2 w-2 rounded-full"
                  style={{ background: r.c }}
                />
                <span className="flex-1 text-xs font-medium">{r.n}</span>
                <span
                  className="sf-num text-[11px]"
                  style={{ color: "var(--sf-text-3)" }}
                >
                  {r.v}
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="mx-auto w-full max-w-[1280px] px-6 py-16 lg:px-12">
        <div className="sf-eyebrow mb-4 text-center">What you get</div>
        <h2 className="mb-14 text-center text-4xl font-semibold tracking-tight lg:text-[40px]">
          Five rings. No nonsense.
        </h2>
        <div className="grid grid-cols-1 gap-3.5 sm:grid-cols-2 lg:grid-cols-5">
          {FEATURES.map((f) => (
            <div
              key={f.title}
              className="rounded-2xl border p-5"
              style={{
                background: "var(--sf-surface)",
                borderColor: "var(--sf-border)",
              }}
            >
              <div className="mb-3.5 text-2xl">{f.icon}</div>
              <div className="mb-1.5 text-sm font-semibold">{f.title}</div>
              <div
                className="text-xs leading-relaxed"
                style={{ color: "var(--sf-text-3)" }}
              >
                {f.desc}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section
        id="how-it-works"
        className="mx-auto w-full max-w-[1280px] px-6 py-16 lg:px-12"
      >
        <div className="sf-eyebrow mb-4 text-center">How it works</div>
        <h2 className="mb-12 text-center text-3xl font-semibold tracking-tight lg:text-[36px]">
          Three steps to a habit that sticks.
        </h2>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          {HOW_IT_WORKS.map((s) => (
            <div
              key={s.step}
              className="rounded-2xl border p-6"
              style={{
                background: "var(--sf-surface)",
                borderColor: "var(--sf-border)",
              }}
            >
              <div
                className="sf-num mb-4 inline-flex h-9 w-9 items-center justify-center rounded-full text-base font-semibold"
                style={{
                  background:
                    "linear-gradient(135deg, var(--sf-ring-move), var(--sf-ring-fuel))",
                  color: "#fff",
                }}
              >
                {s.step}
              </div>
              <div className="mb-2 text-lg font-semibold tracking-tight">
                {s.title}
              </div>
              <div
                className="text-sm leading-relaxed"
                style={{ color: "var(--sf-text-3)" }}
              >
                {s.desc}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Comparison */}
      <section
        id="compare"
        className="mx-auto w-full max-w-[1280px] px-6 py-16 lg:px-12"
      >
        <div className="sf-eyebrow mb-4 text-center">How it compares</div>
        <h2 className="mb-12 text-center text-3xl font-semibold tracking-tight lg:text-[36px]">
          StreakFlow vs other habit trackers
        </h2>
        <div
          className="overflow-x-auto rounded-2xl border"
          style={{
            background: "var(--sf-surface)",
            borderColor: "var(--sf-border)",
          }}
        >
          <table className="w-full min-w-[560px] text-sm">
            <thead>
              <tr style={{ borderBottom: "1px solid var(--sf-border)" }}>
                <th
                  className="px-5 py-3.5 text-left font-semibold"
                  style={{ color: "var(--sf-text-2)" }}
                >
                  Feature
                </th>
                <th className="px-3 py-3.5 font-semibold">StreakFlow</th>
                <th
                  className="px-3 py-3.5 font-medium"
                  style={{ color: "var(--sf-text-3)" }}
                >
                  Habitica
                </th>
                <th
                  className="px-3 py-3.5 font-medium"
                  style={{ color: "var(--sf-text-3)" }}
                >
                  Streaks
                </th>
                <th
                  className="px-3 py-3.5 font-medium"
                  style={{ color: "var(--sf-text-3)" }}
                >
                  Notion
                </th>
              </tr>
            </thead>
            <tbody>
              {COMPARE_ROWS.map((r, i) => (
                <tr
                  key={r.feature}
                  style={{
                    borderTop:
                      i === 0 ? "none" : "1px solid var(--sf-divider)",
                  }}
                >
                  <td
                    className="px-5 py-3"
                    style={{ color: "var(--sf-text-2)" }}
                  >
                    {r.feature}
                  </td>
                  <td className="px-3 py-3 text-center">
                    {r.sf ? (
                      <span style={{ color: "var(--sf-success)" }}>✓</span>
                    ) : (
                      <span style={{ color: "var(--sf-text-3)" }}>—</span>
                    )}
                  </td>
                  <td className="px-3 py-3 text-center">
                    {r.habitica ? (
                      <span style={{ color: "var(--sf-text-2)" }}>✓</span>
                    ) : (
                      <span style={{ color: "var(--sf-text-3)" }}>—</span>
                    )}
                  </td>
                  <td className="px-3 py-3 text-center">
                    {r.streaks ? (
                      <span style={{ color: "var(--sf-text-2)" }}>✓</span>
                    ) : (
                      <span style={{ color: "var(--sf-text-3)" }}>—</span>
                    )}
                  </td>
                  <td className="px-3 py-3 text-center">
                    {r.notion ? (
                      <span style={{ color: "var(--sf-text-2)" }}>✓</span>
                    ) : (
                      <span style={{ color: "var(--sf-text-3)" }}>—</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p
          className="mt-4 text-center text-xs"
          style={{ color: "var(--sf-text-3)" }}
        >
          Based on publicly available feature lists as of 2026. Things change —
          this page does too.
        </p>
      </section>

      {/* FAQ */}
      <section
        id="faq"
        className="mx-auto w-full max-w-[860px] px-6 py-16 lg:px-12"
      >
        <div className="sf-eyebrow mb-4 text-center">Questions</div>
        <h2 className="mb-12 text-center text-3xl font-semibold tracking-tight lg:text-[36px]">
          Frequently asked
        </h2>
        <div className="flex flex-col gap-3">
          {FAQ_ITEMS.map((item) => (
            <details
              key={item.q}
              className="group rounded-2xl border p-5"
              style={{
                background: "var(--sf-surface)",
                borderColor: "var(--sf-border)",
              }}
            >
              <summary
                className="flex cursor-pointer list-none items-center justify-between text-[15px] font-semibold"
              >
                <span>{item.q}</span>
                <svg
                  className="ml-4 shrink-0 transition-transform group-open:rotate-45"
                  width="18"
                  height="18"
                  viewBox="0 0 18 18"
                  fill="none"
                  aria-hidden
                >
                  <path
                    d="M9 3v12M3 9h12"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                  />
                </svg>
              </summary>
              <p
                className="mt-3 text-sm leading-relaxed"
                style={{ color: "var(--sf-text-2)" }}
              >
                {item.a}
              </p>
            </details>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto w-full max-w-[1280px] px-6 py-16 lg:px-12">
        <div
          className="flex flex-col items-center gap-4 rounded-3xl border p-10 text-center lg:p-14"
          style={{
            background:
              "radial-gradient(ellipse at top, rgba(255,179,64,0.10), transparent 70%), var(--sf-surface)",
            borderColor: "var(--sf-border)",
          }}
        >
          <h2 className="text-3xl font-semibold tracking-tight lg:text-[36px]">
            Start your first streak today.
          </h2>
          <p
            className="max-w-[440px] text-sm leading-relaxed"
            style={{ color: "var(--sf-text-2)" }}
          >
            Free forever. No card. No ads. Your data stays yours.
          </p>
          <Link
            href="/signup"
            className="mt-2 inline-flex items-center gap-2 rounded-lg px-6 py-3.5 text-[15px] font-semibold"
            style={{ background: "var(--sf-text)", color: "var(--sf-bg)" }}
          >
            Start free
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
              <path
                d="M3 7h8M7 3l4 4-4 4"
                stroke="currentColor"
                strokeWidth="1.7"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer
        className="mx-auto mt-8 flex w-full max-w-[1280px] items-center justify-between border-t px-6 py-10 lg:px-12"
        style={{ borderColor: "var(--sf-border)" }}
      >
        <div className="text-xs" style={{ color: "var(--sf-text-3)" }}>
          © {new Date().getFullYear()} StreakFlow
        </div>
        <div
          className="flex gap-5 text-xs"
          style={{ color: "var(--sf-text-3)" }}
        >
          <a
            href="https://github.com/avinashchavan1/streakflow"
            target="_blank"
            rel="noreferrer"
          >
            GitHub
          </a>
        </div>
      </footer>
    </div>
  );
}
